name: puppeteer_page_walker
description: A wrapper library of puppeteer for humane scraping.
version: 0.2.0
author: YusukeIwaki
homepage: https://github.com/YusukeIwaki/puppeteer-dart-page-walker
repository: https://github.com/YusukeIwaki/puppeteer-dart-page-walker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  puppeteer: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
